### ISSUE TITLE
[Feature Request] 이름 중복 체크 관련

### ISSUE THREAD

**Issue by YukihoAA** [k4584587/Modular-Auto-Toggle#2]
여러 아바타에서 Auto Toggle 툴을 사용할 때 메뉴 아이템의 이름이 같으면 이름이 중복된다는 오류가 표시됩니다.

실제 동작에서는 이름이 같은 아이템이 있더라도 정상 동작하므로 중복 이름에 대한 체크를 빼거나, 
Group_, Toggle_을 접두사로 붙이는 것 처럼 아바타 이름을 접두사로 붙이게 바꾸면 여러 아바타에서 사용하기 좋을 것 같습니다.

**Comment by k4584587** [comment]
조언 감사합니다.  다음 업데이트 작업시 확인해보겠습니다.
